export const sudoCommand = {
  kind: "sudo",
  output: `[sudo] password for visitor: **********
[WARN] Permission override accepted. Initiating root purge...
[WARN] Deleting root filesystem / ...
[WARN] Unmounting /dev/panda0 ...
[FAIL] Segmentation fault at 0xDEADBEEF: kernel protected by mascot.
[INFO] Restoring snapshot from /backup/portfolio.sys ...
[OK] Core system restored in 12ms. Nice try, hacker! ʕ•ᴥ•ʔ`,
};
